# Generated by Django 4.1.1 on 2022-09-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cbv.product',),
        ),
    ]
