# Generated by Django 4.1.1 on 2022-10-04 17:05

from django.db import migrations, models
import mdls.validation


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0002_alter_main_descrip_alter_main_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(max_length=125, validators=[mdls.validation.not_omar_in]),
        ),
    ]
