# Generated by Django 4.1.1 on 2022-10-04 19:42

from django.db import migrations, models
import mdls.validation


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0003_alter_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(max_length=125, validators=[mdls.validation.not_omar_in, mdls.validation.blocks]),
        ),
    ]
