# Generated by Django 4.1.1 on 2022-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0004_alter_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='state',
            field=models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=25),
        ),
    ]
