# Generated by Django 4.1.1 on 2022-10-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0006_main_create_main_updated_main_when_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='when_public',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
