# Generated by Django 4.1.1 on 2022-10-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdls', '0007_alter_main_when_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ['-updated', '-create'], 'verbose_name': 'Blogs', 'verbose_name_plural': 'Model Blogs'},
        ),
        migrations.AddField(
            model_name='main',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
