# Generated by Django 4.1 on 2022-08-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'description')},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
