# Generated by Django 4.1 on 2022-08-29 17:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_unique_together_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
    ]
