# Generated by Django 4.1.1 on 2022-09-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('descrip', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
