# Generated by Django 4.1.1 on 2022-09-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descrip',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
