# Generated by Django 4.1.1 on 2022-09-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_publish_date_blog_view_count_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 15, 51, 7, 84839, tzinfo=datetime.timezone.utc)),
        ),
    ]
