# Generated by Django 4.1.1 on 2022-09-09 15:59

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='validate',
            field=models.CharField(blank=True, max_length=125, null=True, validators=[blogs.validators.validate_for_email]),
        ),
    ]
