# Generated by Django 4.1.1 on 2022-09-09 16:02

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='validate',
            field=models.CharField(blank=True, max_length=125, null=True, unique=True, validators=[blogs.validators.validate_for_email, blogs.validators.validate_for_omar]),
        ),
    ]
