# Generated by Django 4.1.1 on 2022-09-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(error_messages={'unique': 'Please Put this unique'}, help_text='Must Be uniquq', max_length=125),
        ),
    ]
